asset_path: /home/mrao/frankatask/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/manipulation/lift/config/bimanual_ur5/ur5e_allegro/robots/dual_ur5e_allegro.urdf
usd_dir: /home/mrao/frankatask/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/manipulation/lift/config/bimanual_ur5/agents/ur5e_allegro/robots
usd_file_name: null
force_usd_conversion: false
make_instanceable: true
import_inertia_tensor: true
fix_base: true
merge_fixed_joints: false
self_collision: false
default_drive_type: none
override_joint_dynamics: false
default_drive_stiffness: 0.0
default_drive_damping: 0.0
link_density: 0.0
convex_decompose_mesh: false
func: omni.isaac.lab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: false
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: 5.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: false
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: true
  solver_position_iteration_count: 8
  solver_velocity_iteration_count: 1
  sleep_threshold: null
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-01-21 at 07:13:46.
##
